<a href="https://colab.research.google.com/github/dm8788maut-a11y/PORTAFOLIO/blob/main/U7Sesion_5_Ejercicios_1053558788.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#EJERCICIO 1
#DataFrame: Crea un programa que utilice la librería Pandas para crear un DataFrame con la siguiente información sobre 4 estudiantes: nombres, edades y calificaciones. Muestra el DataFrame resultante.
import pandas as pd
datos_estudiantes = {'NOMBRE':['Juan','Andrés', 'Mariana','Laura'],'EDADES':['23','18','32','28'],'CALIFICAICONES':['2.5','4.0','3.6','2.8']}
df_estudiantes = pd.DataFrame(datos_estudiantes)
print(df_estudiantes)

    NOMBRE EDADES CALIFICAICONES
0     Juan     23            2.5
1   Andrés     18            4.0
2  Mariana     32            3.6
3    Laura     28            2.8


In [ ]:
#Ejercicio 2
#Manipulación básica con pandas
import pandas as pd
data = {'NOMBRE':['Juan','Andrés', 'Mariana','Laura'],'EDADES':['23','18','32','28'],'CIUDAD':['Buenavenura','Restrepo','Cali','Valledupar']}
datos = pd.DataFrame(data)
print(datos)
#crear un filtro de las personas con edad igual o mayor a 25
filtro_edad = datos['EDADES'] >= '25'
personas_mayores_25 = datos[filtro_edad]
print(personas_mayores_25)
#crear una columa llamada categoría
datos['CATEGORIA'] = ['ADULTO' if edad >= '25' else 'MENOR' for edad in datos['EDADES']]
print(datos)


    NOMBRE EDADES       CIUDAD
0     Juan     23  Buenavenura
1   Andrés     18     Restrepo
2  Mariana     32         Cali
3    Laura     28   Valledupar
    NOMBRE EDADES      CIUDAD
2  Mariana     32        Cali
3    Laura     28  Valledupar
    NOMBRE EDADES       CIUDAD CATEGORIA
0     Juan     23  Buenavenura     MENOR
1   Andrés     18     Restrepo     MENOR
2  Mariana     32         Cali    ADULTO
3    Laura     28   Valledupar    ADULTO


In [ ]:
#EJERCICIO 3
#Operación básica con NumPy
import numpy as np
array = np.array([1,2,3,4,5])
print(array)
#Calcula la media y la desviación estándar del array vector.
media = np.mean(array)
desviacion_estandar = np.std(array)
print(media)
print(desviacion_estandar)
# Crea una matriz llamada matriz con 3 filas y 2 columnas, llenándola con números aleatorios entre 1 y 10.
matriz = np.random.randint(1,11,size=(3,2))
print(matriz)
#Multiplica todos los elementos de la matriz por 2.
matriz_multiplicada = matriz * 2
print(matriz_multiplicada)
#Calcula la suma de todos los elementos de la matriz.
suma_matriz = np.sum(matriz)
print(suma_matriz)

[1 2 3 4 5]
3.0
1.4142135623730951
[[10  4]
 [ 9  3]
 [ 9  7]]
[[20  8]
 [18  6]
 [18 14]]
42


In [ ]:
#EJERCICIO 4
import pandas as pd
datos_iris=pd.read_csv('iris.csv')
print(datos_iris)
# mostrar las primeras 5 filas del df
primeras_filas = datos_iris.head(5)
print(primeras_filas)
#Filtrar las filas donde la especie sea "iris_setosa".
filtro_especie = datos_iris[datos_iris['species'] == 'setosa']
print(filtro_especie)
# Calcular la media de la longitud de los sépalos (sepal_length) para las filas filtradas
media_sepal_length = filtro_especie['sepal_length'].astype(float).mean()
print(media_sepal_length)
#Mostrar los resultados en formato tabular.


     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9     

In [ ]:
# EJERCICIO 5
#Concatenación de DataFrames: Crea un programa que utilice Pandas para realizar las siguientes tareas:

#Crea dos DataFrames llamados df1 y df2 con las siguientes columnas: A, B, C.
#Llena ambos DataFrames con datos.
#Concatena verticalmente los dos DataFrames para crear un nuevo DataFrame llamado df_concat.
#Muestra por pantalla el resultado de la concatenación.
import pandas as pd
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})
df2 = pd.DataFrame({'A':[10,11,12],'B':[13,14,15],'C':[16,17,18]})
print(df1)
print(df2)
df_concat = pd.concat([df1, df2], ignore_index=True)
print(df_concat)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
    A   B   C
0  10  13  16
1  11  14  17
2  12  15  18
    A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
3  10  13  16
4  11  14  17
5  12  15  18
